# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ca3e88fd3d3ca1976f3e419e40a3eea51878c5cab8c9df94c823f928533c442e655eb46977eee6fa1fe6c5cb69b56e1f2068f6c3fbdb91c0867e97d953c858

test:
  secret_key_base: a84c4dbc8555cda2d13b9e6b51967fd539482fd9649e9b19dad5b99d7852e87ecdcfe9421d46757217e7b861c9fbcecf0ba60e58c9e2d82ebf132bd4eaabdfd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
